# --------------------------------------------------------------
#  expense_tracker/main.py
# --------------------------------------------------------------
import base64
import os
from datetime import date, datetime
from typing import List, Optional

import httpx
from fastapi import APIRouter, FastAPI, File, HTTPException, UploadFile, Depends, Query
from sqlmodel import Session, select
from dotenv import load_dotenv

from backend.database import get_session
from backend.models import Bill, BillCategory, BillResponse, BillStatus, BillUpdate

# --------------------------------------------------------------
#  Load environment (Groq API key)
# --------------------------------------------------------------
load_dotenv()
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise RuntimeError(
        "GROQ_API_KEY not found – set it in a .env file or the environment")

# --------------------------------------------------------------
#  FastAPI app
# --------------------------------------------------------------
app = FastAPI(title="Expense Tracker (Groq OCR)")
router = APIRouter()
app.include_router(router)  # <-- registers the /bills/upload/ endpoint


# --------------------------------------------------------------
#  Groq OCR helper
# --------------------------------------------------------------
GROQ_ENDPOINT = "https://api.groq.com/openai/v1/chat/completions"
# replace with the exact vision model you have
GROQ_MODEL = "qwen/qwen3.8-27b"


async def extract_bill_data_with_groq(image_bytes: bytes) -> dict:
    """Send image to Groq Vision model and return a dict with date, vendor_name, total_amount."""
    b64_image = base64.b64encode(image_bytes).decode()
    data_url = f"data:image/jpeg;base64,{b64_image}"

    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an OCR assistant. Extract the **date**, **vendor name** "
                    "and **total amount** from the attached receipt image. "
                    "Return a **valid JSON object** with exactly the keys: "
                    "`bill_date`, `vendor_name`, `total_amount`. "
                    "Date must be ISO‑8601 (YYYY‑MM‑DD). Amount is a number (float)."
                ),
            },
            {
                "role": "user",
                "content": [{"type": "image_url", "image_url": {"url": data_url}}],
            },
        ],
        "temperature": 0.0,
        "max_tokens": 256,
    }

    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json",
    }

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(GROQ_ENDPOINT, json=payload, headers=headers)

    if resp.status_code != 200:
        raise HTTPException(
            status_code=502,
            detail=f"Groq API error {resp.status_code}: {resp.text}",
        )

    data = resp.json()
    try:
        raw_text = data["choices"][0]["message"]["content"]
        # Groq may return the JSON with surrounding backticks or extra text.
        # We'll try to locate the first `{` and the matching `}`.
        start = raw_text.find("{")
        end = raw_text.rfind("}") + 1
        json_str = raw_text[start:end]
        # safe because we control the prompt & model is deterministic
        extracted = eval(json_str)
    except Exception as exc:
        raise HTTPException(
            status_code=422,
            detail=f"Failed to parse Groq response: {exc}",
        )

    # Minimal validation – make sure all three keys exist
    required_keys = {"bill_date", "vendor_name", "total_amount"}
    if not required_keys.issubset(extracted):
        raise HTTPException(
            status_code=422,
            detail=f"Groq response missing required keys. Got: {list(extracted.keys())}",
        )
    return extracted


@router.post(
    "/bills/upload",
    response_model=BillResponse,
    summary="Upload a receipt image, extract data via Groq, store as pending",
    tags=["Bills"],
)
async def upload_bill(
    file: UploadFile = File(...),
    session: Session = Depends(get_session),
):
    """
    1️⃣ Read the uploaded image (in‑memory – you may add size limits later).  
    2️⃣ Call `_extract_with_groq` to get `bill_date`, `vendor_name` and `total_amount`.  
    3️⃣ Insert a new `Bill` row with `status = pending`.  
    4️⃣ Return the created record (including its autogenerated `id`).
    """
    # ----- 1. read file -------------------------------------------------
    image_bytes = await file.read()
    if not image_bytes:
        raise HTTPException(status_code=400, detail="Empty file uploaded")

    # ----- 2. OCR via Groq -----------------------------------------------
    extracted = await extract_bill_data_with_groq(image_bytes)

    # Convert strings to proper Python types
    try:
        billdate = date.fromisoformat(extracted["bill_date"])
        vendor = str(extracted["vendor_name"])
        amount = float(extracted["total_amount"])
    except Exception as exc:
        raise HTTPException(
            status_code=422,
            detail=f"Invalid data returned from Groq: {exc}",
        )

    # ----- 3. Persist the pending bill ------------------------------------
    new_bill = Bill(
        bill_date=billdate,
        vendor_name=vendor,
        total_amount=amount,
        category=BillCategory.miscellaneous,
        status=BillStatus.pending,
    )
    session.add(new_bill)
    session.commit()
    session.refresh(new_bill)

    # ----- 4. Return the created record ----------------------------------
    return new_bill


@router.get("/bills/review", response_model=List[Bill])
def review_bills(
    *,
    session: Session = Depends(get_session),
    skip: int = Query(0, ge=0),
    limit: int = Query(50, le=200),
    status: Optional[BillStatus] = None,
    vendor_name: Optional[str] = None,
    category: Optional[BillCategory] = None,
):
    """
    Return a paginated list of bills.
    Optional filters: status, vendor_name.
    """
    stmt = (
        select(Bill)
        .offset(skip)
        .limit(limit)
    )
    if status:
        stmt = stmt.where(Bill.status == status)
    if status:
        stmt = stmt.where(Bill.category == category)
    if vendor_name:
        stmt = stmt.where(Bill.vendor_name.ilike(f"%{vendor_name}%"))

    results = session.exec(stmt).all()

    return results

# 🧩 1. PUT: Full rewrite / replace


@router.put("/bills/{bill_id}", response_model=BillResponse)
def update_bill_full(bill_id: int, updated_bill: BillUpdate, session: Session = Depends(get_session)):
    db_bill = session.get(Bill, bill_id)
    if not db_bill:
        raise HTTPException(status_code=404, detail="Bill not found")

    # Overwrite all data fields
    # Extract data safely, bypassing strict model validation rules during dump
    bill_data = updated_bill.model_dump(mode="python", exclude={"id"})
    db_bill.sqlmodel_update(bill_data)
    db_bill.reviewed_at = datetime.utcnow()

    session.add(db_bill)
    session.commit()
    session.refresh(db_bill)
    return db_bill
